### PR TITLE
Optical functions for proton reconstruction

### PR DESCRIPTION
**Pull request by forthommel**
Added optical functions for proton reconstruction algorithm

### CODE REVIEW

**Comment by forthommel** [comment]
This PR is intended to strip this external from https://github.com/cms-sw/cmssw/pull/25495. Therefore all tests for this latter will depend on this https://github.com/cms-sw/cmsdist/issues/4680 update.

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by mrodozov** [comment]
Resolve: https://github.com/cms-sw/cmsdist/issues/4680

**Comment by slava77** [comment]
@forthommel 

I'm not sure about the proper location re cms-sw/cmssw#25495.
- The consumer code is in  RecoCTPPS/ProtonReconstruction => placing the files in RecoCTPPS-TotemRPLocal doesn't seem appropriate. 
    - do we expect any other consumers to this?
- The ES producer in the PR is still misplaced in CondFormats/CTPPSReadoutObjects as mentioned in https://github.com/cms-sw/cmssw/pull/25495/files#r246111419

I think that the right place for this file will be in the same package-like data location as the CTPPSOpticalFunctionsESSource which needs this file.

**Comment by jan-kaspar** [comment]
> @forthommel
> 
> I'm not sure about the proper location re [cms-sw/cmssw#25495](https://github.com/cms-sw/cmssw/pull/25495).
> 
> * The consumer code is in  RecoCTPPS/ProtonReconstruction => placing the files in RecoCTPPS-TotemRPLocal doesn't seem appropriate.
>   
>   * do we expect any other consumers to this?
> * The ES producer in the PR is still misplaced in CondFormats/CTPPSReadoutObjects as mentioned in https://github.com/cms-sw/cmssw/pull/25495/files#r246111419
> 
> I think that the right place for this file will be in the same package-like data location as the CTPPSOpticalFunctionsESSource which needs this file.

The direct consumer code is currently in ``CondFormats/CTPPSReadoutObjects`` and this should be the only one. All other modules should access these data via EventSetup.

I am aware of the non-conform placement of the ESSource (in fact there are several of them in https://github.com/cms-sw/cmssw/pull/25495). I tried to [ask](https://github.com/cms-sw/cmssw/pull/25495#issuecomment-452784651) for a more suitable placement, but I can't find any answer. Could you please suggest one? Thanks in advance!

**Comment by slava77** [comment]
> I am aware of the non-conform placement of the ESSource (in fact there are several of them in [cms-sw/cmssw#25495](https://github.com/cms-sw/cmssw/pull/25495)). I tried to [ask](https://github.com/cms-sw/cmssw/pull/25495#issuecomment-452784651) for a more suitable placement, but I can't find any answer. Could you please suggest one? Thanks in advance!

I tried to follow up at the origin/source of this
https://github.com/cms-sw/cmssw/pull/25495#issuecomment-461048205

**Comment by jan-kaspar** [comment]
> > I am aware of the non-conform placement of the ESSource (in fact there are several of them in [cms-sw/cmssw#25495](https://github.com/cms-sw/cmssw/pull/25495)). I tried to [ask](https://github.com/cms-sw/cmssw/pull/25495#issuecomment-452784651) for a more suitable placement, but I can't find any answer. Could you please suggest one? Thanks in advance!
> 
> I tried to follow up at the origin/source of this
> [cms-sw/cmssw#25495 (comment)](https://github.com/cms-sw/cmssw/pull/25495#issuecomment-461048205)

Many thanks! Following your suggestion, the ESProducers have been moved to `CalibPPS/ESProducers`. Coming back to this PR, would `CalibPPS-ESProducers` be more appropriate? Or would you have preference for `RecoCTPPS-ProtonReconstruction` (main consumer)? For sure, the life time of this one file should be short (~a month) before it is replace with DB. Consequently, I'd personally favour an "easy" solution.

**Comment by slava77** [comment]
On 2/13/19 7:22 AM, jan-kaspar wrote:
> Many thanks! Following your suggestion, the ESProducers have been moved
> to |CalibPPS/ESProducers|. Coming back to this PR, would
> |CalibPPS-ESProducers| be more appropriate? Or would you have preference
> for |RecoCTPPS-ProtonReconstruction| (main consumer)? For sure, the life
> time of this one file should be short (~a month) before it is replace
> with DB. Consequently, I'd personally favour an "easy" solution.


I propose to use CalibPPS-ESProducers
This will also allow for other consumers to use this in a
straightforward way wrt possible dependencies.

**Comment by jan-kaspar** [comment]
> On 2/13/19 7:22 AM, jan-kaspar wrote: Many thanks! Following your suggestion, the ESProducers have been moved to |CalibPPS/ESProducers|. Coming back to this PR, would |CalibPPS-ESProducers| be more appropriate? Or would you have preference for |RecoCTPPS-ProtonReconstruction| (main consumer)? For sure, the life time of this one file should be short (~a month) before it is replace with DB. Consequently, I'd personally favour an "easy" solution.
> I propose to use CalibPPS-ESProducers This will also allow for other consumers to use this in a straightforward way wrt possible dependencies.

Thanks @slava77 ! @forthommel would you be available to take care, please?

**Comment by forthommel** [comment]
For sure ! @smuzaffar, @iahmad-khan, @slava77, being a simple user I do not have any repository creation permission to the cms-data group. Would it please be possible for you to create this cms-data/CalibPPS-ESProducers repo?

**Comment by mrodozov** [comment]
if only the root file is needed for the other repo please see the link above sign it and we can continue from there

**Comment by forthommel** [comment]
Very good, @mrodozov! Many thanks!

**Pull request closed without merging**
