### PR TITLE
Diamond timing calibration example

### PR DESCRIPTION
**Pull request by forthommel**
Example of calibration file for diamond timing calibration conditions format PR.

### CODE REVIEW

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by smuzaffar** [comment]
ping @slava77,@perrotta

**Comment by slava77** [comment]
@forthommel 
what is the purpose of this calibration file and what is the plan to move this to the DB?
If the CondFormat for this already exists, I propose to move the files to the corresponding Cond\* package.

**Comment by forthommel** [comment]
@slava77 
Indeed, reading it again I see the PR description was sub-optimal! This file may be used as a test for the reviewers of https://github.com/cms-sw/cmssw/pull/26207. I believe this PR may be closed (hence without merging) when this latter gets merged.

**Comment by forthommel** [comment]
Closing as cms-sw/cmssw#26207 is now merged.

**Pull request closed without merging**
